### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jayce-leathers** [kylesuss/fresh-transmission#6]
I notice your package.json specifies this as licensed under MIT. You don't have a license file checked in though. Is this licensed under MIT? And if so could you add a file specifying the license? I'd like to use this as the base for an application I'm building. Thanks very much!

**Comment by jayce-leathers** [comment]
bump

**Comment by kylesuss** [comment]
@jayce-leathers Hey sorry, I totally missed this. If its of any use to you still, I added the license to the repo for you -- MIT was the desired license.
